package constructorAST.errors;

public enum TipoError {
	DUPIDEN, NOIDEN, TYPEOP, TYPECOND, TYPEASIG, TYPEASIG_TERNARIO_CONDICION, TYPEASIG_TERNARIO_LEFT_TYPE,
	TYPEASIG_TERNARIO_A_TYPE, TYPEASIG_TERNARIO_B_TYPE, TYPEWHILE, TYPEFOR, TYPEASIG_TERNARIO, NOVALUE, DIV_POR_0,
	MAX_IT_WHILE, MAX_IT_FOR
}