
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Jan 18 13:01:22 CET 2026
//----------------------------------------------------

package constructorAST.constructorast;

import java_cup.runtime.*;
import constructorAST.alex.AnalizadorLexicoTiny;
import constructorAST.alex.UnidadLexica;
import constructorAST.alex.TokenValue;
import constructorAST.errors.GestionErroresTiny;
import constructorAST.ast.*;
import java.util.LinkedList;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.ComplexSymbolFactory.Location;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Sun Jan 18 13:01:22 CET 2026
  */
public class AnalizadorSintacticoTiny extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintacticoTiny() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoTiny(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoTiny(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\053\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\002\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\007\006\000\002\014\005\000\002" +
    "\013\017\000\002\010\005\000\002\010\005\000\002\010" +
    "\005\000\002\006\012\000\002\004\006\000\002\004\002" +
    "\000\002\011\011\000\002\012\014\000\002\015\005\000" +
    "\002\015\005\000\002\015\003\000\002\016\005\000\002" +
    "\016\005\000\002\016\003\000\002\017\005\000\002\017" +
    "\003\000\002\020\005\000\002\020\005\000\002\020\005" +
    "\000\002\020\005\000\002\020\003\000\002\021\005\000" +
    "\002\021\005\000\002\021\003\000\002\022\003\000\002" +
    "\022\003\000\002\022\003\000\002\022\003\000\002\022" +
    "\003\000\002\022\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\151\000\022\002\ufffe\004\016\006\006\007\011\010" +
    "\017\011\022\012\013\015\014\001\002\000\024\002\ufffd" +
    "\004\ufffd\006\ufffd\007\ufffd\010\ufffd\011\ufffd\012\ufffd\015" +
    "\ufffd\037\ufffd\001\002\000\024\002\ufffc\004\ufffc\006\ufffc" +
    "\007\ufffc\010\ufffc\011\ufffc\012\ufffc\015\ufffc\037\ufffc\001" +
    "\002\000\004\034\146\001\002\000\024\002\ufffb\004\ufffb" +
    "\006\ufffb\007\ufffb\010\ufffb\011\ufffb\012\ufffb\015\ufffb\037" +
    "\ufffb\001\002\000\024\002\ufffa\004\ufffa\006\ufffa\007\ufffa" +
    "\010\ufffa\011\ufffa\012\ufffa\015\ufffa\037\ufffa\001\002\000" +
    "\004\034\130\001\002\000\004\002\001\001\002\000\004" +
    "\015\126\001\002\000\004\024\110\001\002\000\004\002" +
    "\107\001\002\000\004\034\031\001\002\000\004\015\027" +
    "\001\002\000\024\002\ufff8\004\ufff8\006\ufff8\007\ufff8\010" +
    "\ufff8\011\ufff8\012\ufff8\015\ufff8\037\ufff8\001\002\000\024" +
    "\002\ufff9\004\ufff9\006\ufff9\007\ufff9\010\ufff9\011\ufff9\012" +
    "\ufff9\015\ufff9\037\ufff9\001\002\000\004\015\025\001\002" +
    "\000\024\002\ufffe\004\016\006\006\007\011\010\017\011" +
    "\022\012\013\015\014\037\ufffe\001\002\000\006\002\uffff" +
    "\037\uffff\001\002\000\004\040\026\001\002\000\024\002" +
    "\ufff3\004\ufff3\006\ufff3\007\ufff3\010\ufff3\011\ufff3\012\ufff3" +
    "\015\ufff3\037\ufff3\001\002\000\004\040\030\001\002\000" +
    "\024\002\ufff4\004\ufff4\006\ufff4\007\ufff4\010\ufff4\011\ufff4" +
    "\012\ufff4\015\ufff4\037\ufff4\001\002\000\016\013\034\014" +
    "\036\015\035\016\032\017\040\034\033\001\002\000\040" +
    "\020\uffdc\021\uffdc\022\uffdc\023\uffdc\025\uffdc\026\uffdc\027" +
    "\uffdc\030\uffdc\031\uffdc\032\uffdc\033\uffdc\035\uffdc\040\uffdc" +
    "\042\uffdc\044\uffdc\001\002\000\016\013\034\014\036\015" +
    "\035\016\032\017\040\034\033\001\002\000\040\020\uffda" +
    "\021\uffda\022\uffda\023\uffda\025\uffda\026\uffda\027\uffda\030" +
    "\uffda\031\uffda\032\uffda\033\uffda\035\uffda\040\uffda\042\uffda" +
    "\044\uffda\001\002\000\040\020\uffd8\021\uffd8\022\uffd8\023" +
    "\uffd8\025\uffd8\026\uffd8\027\uffd8\030\uffd8\031\uffd8\032\uffd8" +
    "\033\uffd8\035\uffd8\040\uffd8\042\uffd8\044\uffd8\001\002\000" +
    "\040\020\uffd9\021\uffd9\022\uffd9\023\uffd9\025\uffd9\026\uffd9" +
    "\027\uffd9\030\uffd9\031\uffd9\032\uffd9\033\uffd9\035\uffd9\040" +
    "\uffd9\042\uffd9\044\uffd9\001\002\000\040\020\uffdd\021\uffdd" +
    "\022\uffdd\023\uffdd\025\uffdd\026\uffdd\027\uffdd\030\uffdd\031" +
    "\uffdd\032\uffdd\033\uffdd\035\uffdd\040\uffdd\042\uffdd\044\uffdd" +
    "\001\002\000\040\020\uffdb\021\uffdb\022\uffdb\023\uffdb\025" +
    "\uffdb\026\uffdb\027\uffdb\030\uffdb\031\uffdb\032\uffdb\033\uffdb" +
    "\035\uffdb\040\uffdb\042\uffdb\044\uffdb\001\002\000\040\020" +
    "\uffe0\021\uffe0\022\uffe0\023\uffe0\025\uffe0\026\uffe0\027\uffe0" +
    "\030\uffe0\031\uffe0\032\065\033\064\035\uffe0\040\uffe0\042" +
    "\uffe0\044\uffe0\001\002\000\034\020\uffe5\021\uffe5\022\uffe5" +
    "\023\uffe5\025\uffe5\026\062\027\061\030\057\031\060\035" +
    "\uffe5\040\uffe5\042\uffe5\044\uffe5\001\002\000\024\020\uffe7" +
    "\021\uffe7\022\uffe7\023\uffe7\025\055\035\uffe7\040\uffe7\042" +
    "\uffe7\044\uffe7\001\002\000\022\020\053\021\052\022\uffea" +
    "\023\uffea\035\uffea\040\uffea\042\uffea\044\uffea\001\002\000" +
    "\010\022\050\023\047\035\046\001\002\000\004\036\075" +
    "\001\002\000\016\013\034\014\036\015\035\016\032\017" +
    "\040\034\033\001\002\000\016\013\034\014\036\015\035" +
    "\016\032\017\040\034\033\001\002\000\022\020\053\021" +
    "\052\022\uffec\023\uffec\035\uffec\040\uffec\042\uffec\044\uffec" +
    "\001\002\000\016\013\034\014\036\015\035\016\032\017" +
    "\040\034\033\001\002\000\016\013\034\014\036\015\035" +
    "\016\032\017\040\034\033\001\002\000\024\020\uffe9\021" +
    "\uffe9\022\uffe9\023\uffe9\025\055\035\uffe9\040\uffe9\042\uffe9" +
    "\044\uffe9\001\002\000\016\013\034\014\036\015\035\016" +
    "\032\017\040\034\033\001\002\000\034\020\uffe6\021\uffe6" +
    "\022\uffe6\023\uffe6\025\uffe6\026\062\027\061\030\057\031" +
    "\060\035\uffe6\040\uffe6\042\uffe6\044\uffe6\001\002\000\016" +
    "\013\034\014\036\015\035\016\032\017\040\034\033\001" +
    "\002\000\016\013\034\014\036\015\035\016\032\017\040" +
    "\034\033\001\002\000\016\013\034\014\036\015\035\016" +
    "\032\017\040\034\033\001\002\000\016\013\034\014\036" +
    "\015\035\016\032\017\040\034\033\001\002\000\040\020" +
    "\uffe4\021\uffe4\022\uffe4\023\uffe4\025\uffe4\026\uffe4\027\uffe4" +
    "\030\uffe4\031\uffe4\032\065\033\064\035\uffe4\040\uffe4\042" +
    "\uffe4\044\uffe4\001\002\000\016\013\034\014\036\015\035" +
    "\016\032\017\040\034\033\001\002\000\016\013\034\014" +
    "\036\015\035\016\032\017\040\034\033\001\002\000\040" +
    "\020\uffdf\021\uffdf\022\uffdf\023\uffdf\025\uffdf\026\uffdf\027" +
    "\uffdf\030\uffdf\031\uffdf\032\uffdf\033\uffdf\035\uffdf\040\uffdf" +
    "\042\uffdf\044\uffdf\001\002\000\040\020\uffde\021\uffde\022" +
    "\uffde\023\uffde\025\uffde\026\uffde\027\uffde\030\uffde\031\uffde" +
    "\032\uffde\033\uffde\035\uffde\040\uffde\042\uffde\044\uffde\001" +
    "\002\000\040\020\uffe3\021\uffe3\022\uffe3\023\uffe3\025\uffe3" +
    "\026\uffe3\027\uffe3\030\uffe3\031\uffe3\032\065\033\064\035" +
    "\uffe3\040\uffe3\042\uffe3\044\uffe3\001\002\000\040\020\uffe1" +
    "\021\uffe1\022\uffe1\023\uffe1\025\uffe1\026\uffe1\027\uffe1\030" +
    "\uffe1\031\uffe1\032\065\033\064\035\uffe1\040\uffe1\042\uffe1" +
    "\044\uffe1\001\002\000\040\020\uffe2\021\uffe2\022\uffe2\023" +
    "\uffe2\025\uffe2\026\uffe2\027\uffe2\030\uffe2\031\uffe2\032\065" +
    "\033\064\035\uffe2\040\uffe2\042\uffe2\044\uffe2\001\002\000" +
    "\024\020\uffe8\021\uffe8\022\uffe8\023\uffe8\025\055\035\uffe8" +
    "\040\uffe8\042\uffe8\044\uffe8\001\002\000\022\020\053\021" +
    "\052\022\uffeb\023\uffeb\035\uffeb\040\uffeb\042\uffeb\044\uffeb" +
    "\001\002\000\022\004\016\006\006\007\011\010\017\011" +
    "\022\012\013\015\014\037\ufffe\001\002\000\004\037\077" +
    "\001\002\000\026\002\uffef\004\uffef\005\100\006\uffef\007" +
    "\uffef\010\uffef\011\uffef\012\uffef\015\uffef\037\uffef\001\002" +
    "\000\004\036\102\001\002\000\024\002\ufff1\004\ufff1\006" +
    "\ufff1\007\ufff1\010\ufff1\011\ufff1\012\ufff1\015\ufff1\037\ufff1" +
    "\001\002\000\022\004\016\006\006\007\011\010\017\011" +
    "\022\012\013\015\014\037\ufffe\001\002\000\004\037\104" +
    "\001\002\000\024\002\ufff0\004\ufff0\006\ufff0\007\ufff0\010" +
    "\ufff0\011\ufff0\012\ufff0\015\ufff0\037\ufff0\001\002\000\010" +
    "\022\050\023\047\035\106\001\002\000\040\020\uffd7\021" +
    "\uffd7\022\uffd7\023\uffd7\025\uffd7\026\uffd7\027\uffd7\030\uffd7" +
    "\031\uffd7\032\uffd7\033\uffd7\035\uffd7\040\uffd7\042\uffd7\044" +
    "\uffd7\001\002\000\004\002\000\001\002\000\020\013\034" +
    "\014\036\015\035\016\032\017\040\034\033\041\111\001" +
    "\002\000\016\013\034\014\036\015\035\016\032\017\040" +
    "\034\033\001\002\000\010\022\050\023\047\040\113\001" +
    "\002\000\036\002\ufff7\004\ufff7\006\ufff7\007\ufff7\010\ufff7" +
    "\011\ufff7\012\ufff7\013\ufff7\014\ufff7\015\ufff7\016\ufff7\017" +
    "\ufff7\034\ufff7\037\ufff7\001\002\000\010\022\050\023\047" +
    "\042\115\001\002\000\004\004\116\001\002\000\004\043" +
    "\117\001\002\000\016\013\034\014\036\015\035\016\032" +
    "\017\040\034\033\001\002\000\010\022\050\023\047\044" +
    "\121\001\002\000\004\005\122\001\002\000\004\043\123" +
    "\001\002\000\016\013\034\014\036\015\035\016\032\017" +
    "\040\034\033\001\002\000\010\022\050\023\047\040\125" +
    "\001\002\000\024\002\ufff5\004\ufff5\006\ufff5\007\ufff5\010" +
    "\ufff5\011\ufff5\012\ufff5\015\ufff5\037\ufff5\001\002\000\004" +
    "\040\127\001\002\000\024\002\ufff2\004\ufff2\006\ufff2\007" +
    "\ufff2\010\ufff2\011\ufff2\012\ufff2\015\ufff2\037\ufff2\001\002" +
    "\000\004\015\132\001\002\000\016\013\034\014\036\015" +
    "\035\016\032\017\040\034\033\001\002\000\004\024\133" +
    "\001\002\000\016\013\034\014\036\015\035\016\032\017" +
    "\040\034\033\001\002\000\010\022\050\023\047\040\135" +
    "\001\002\000\004\015\136\001\002\000\004\024\144\001" +
    "\002\000\004\035\140\001\002\000\004\036\141\001\002" +
    "\000\022\004\016\006\006\007\011\010\017\011\022\012" +
    "\013\015\014\037\ufffe\001\002\000\004\037\143\001\002" +
    "\000\024\002\uffed\004\uffed\006\uffed\007\uffed\010\uffed\011" +
    "\uffed\012\uffed\015\uffed\037\uffed\001\002\000\016\013\034" +
    "\014\036\015\035\016\032\017\040\034\033\001\002\000" +
    "\010\022\050\023\047\035\ufff6\001\002\000\016\013\034" +
    "\014\036\015\035\016\032\017\040\034\033\001\002\000" +
    "\010\022\050\023\047\035\150\001\002\000\004\036\151" +
    "\001\002\000\022\004\016\006\006\007\011\010\017\011" +
    "\022\012\013\015\014\037\ufffe\001\002\000\004\037\153" +
    "\001\002\000\024\002\uffee\004\uffee\006\uffee\007\uffee\010" +
    "\uffee\011\uffee\012\uffee\015\uffee\037\uffee\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\151\000\024\002\014\003\011\005\022\006\003\007" +
    "\004\010\006\011\007\012\020\013\017\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\022\003\023\005\022\006" +
    "\003\007\004\010\006\011\007\012\020\013\017\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\015\044\016\043" +
    "\017\042\020\041\021\040\022\036\001\001\000\002\001" +
    "\001\000\016\015\104\016\043\017\042\020\041\021\040" +
    "\022\036\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\016\073" +
    "\017\042\020\041\021\040\022\036\001\001\000\014\016" +
    "\050\017\042\020\041\021\040\022\036\001\001\000\002" +
    "\001\001\000\012\017\072\020\041\021\040\022\036\001" +
    "\001\000\012\017\053\020\041\021\040\022\036\001\001" +
    "\000\002\001\001\000\010\020\055\021\040\022\036\001" +
    "\001\000\002\001\001\000\006\021\071\022\036\001\001" +
    "\000\006\021\070\022\036\001\001\000\006\021\067\022" +
    "\036\001\001\000\006\021\062\022\036\001\001\000\002" +
    "\001\001\000\004\022\066\001\001\000\004\022\065\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\003\075\005\022\006\003\007\004" +
    "\010\006\011\007\012\020\013\017\001\001\000\002\001" +
    "\001\000\004\004\100\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\003\102\005\022\006\003\007\004\010" +
    "\006\011\007\012\020\013\017\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\015\111\016\043\017\042\020\041" +
    "\021\040\022\036\001\001\000\016\015\113\016\043\017" +
    "\042\020\041\021\040\022\036\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\015\117\016\043\017\042\020\041" +
    "\021\040\022\036\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\015\123\016\043\017\042" +
    "\020\041\021\040\022\036\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\007\130\001\001\000\016\015\133\016\043\017\042\020" +
    "\041\021\040\022\036\001\001\000\002\001\001\000\016" +
    "\015\111\016\043\017\042\020\041\021\040\022\036\001" +
    "\001\000\002\001\001\000\004\014\136\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\003" +
    "\141\005\022\006\003\007\004\010\006\011\007\012\020" +
    "\013\017\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\015\144\016\043\017\042\020\041\021\040\022\036" +
    "\001\001\000\002\001\001\000\016\015\146\016\043\017" +
    "\042\020\041\021\040\022\036\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\003\151\005\022\006\003\007" +
    "\004\010\006\011\007\012\020\013\017\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintacticoTiny$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintacticoTiny$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintacticoTiny$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 
   errores = new GestionErroresTiny();
   AnalizadorLexicoTiny alex = (AnalizadorLexicoTiny)getScanner();
   alex.fijaGestionErrores(errores);

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return getScanner().next_token(); 
    }

 
   private GestionErroresTiny errores;
   public void syntax_error(Symbol unidadLexica) {
     errores.errorSintactico((UnidadLexica)unidadLexica);
   }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintacticoTiny$actions {
  private final AnalizadorSintacticoTiny parser;

  /** Constructor */
  CUP$AnalizadorSintacticoTiny$actions(AnalizadorSintacticoTiny parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoTiny$do_action_part00000000(
    int                        CUP$AnalizadorSintacticoTiny$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoTiny$parser,
    java.util.Stack            CUP$AnalizadorSintacticoTiny$stack,
    int                        CUP$AnalizadorSintacticoTiny$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintacticoTiny$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintacticoTiny$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // P ::= LInst 
            {
              LinkedList<Instruccion> RESULT =null;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = l; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("P",0, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= P EOF 
            {
              Object RESULT =null;
		LinkedList<Instruccion> start_val = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintacticoTiny$parser.done_parsing();
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LInst ::= Inst LInst 
            {
              LinkedList<Instruccion> RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 l.addFirst(inst); RESULT = l; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("LInst",1, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LInst ::= 
            {
              LinkedList<Instruccion> RESULT =null;
		 RESULT = new LinkedList(); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("LInst",1, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Inst ::= Cond 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = inst; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Inst ::= Asig 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = inst; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Inst ::= Decl 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = inst; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Inst ::= While 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = inst; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Inst ::= For 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = inst; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Inst ::= AsigTres 
            {
              Instruccion RESULT =null;
		Instruccion inst = (Instruccion)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = inst; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Inst",3, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Asig ::= IDEN IGUAL E0 PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-3)).value;
		E exp = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		 RESULT = new Asignacion(id.fila, id.columna, id.lexema, exp); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Asig",5, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // AsigSinPC ::= IDEN IGUAL E0 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E exp = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new Asignacion(id.fila, id.columna, id.lexema, exp); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("AsigSinPC",10, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // AsigTres ::= IDEN IGUAL INTERAPERTURA E0 INTERCIERRE IF DOSPUNTOS E0 BARRABAJA ELSE DOSPUNTOS E0 PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-12)).value;
		E exp = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-9)).value;
		E a = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-5)).value;
		E b = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		 RESULT = new AsignacionTres(id.fila, id.columna, id.lexema, exp, a, b); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("AsigTres",9, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Decl ::= TIPO_ENT IDEN PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		 RESULT = new Declaracion(id.fila, id.columna, Type.NUM, id.lexema); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Decl",6, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Decl ::= TIPO_BOOL IDEN PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		 RESULT = new Declaracion(id.fila, id.columna, Type.BOOL, id.lexema); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Decl",6, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Decl ::= TIPO_REAL IDEN PUNTOCOMA 
            {
              Instruccion RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		 RESULT = new Declaracion(id.fila, id.columna, Type.REAL, id.lexema); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Decl",6, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Cond ::= IF PAP E0 PCIERRE CAP LInst CCIERRE ElseCase 
            {
              Instruccion RESULT =null;
		TokenValue i = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-7)).value;
		E exp = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-5)).value;
		LinkedList<Instruccion> inst_if = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		LinkedList<Instruccion> inst_else = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new Condicional(i.fila, i.columna, exp, inst_if, inst_else); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("Cond",4, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ElseCase ::= ELSE CAP LInst CCIERRE 
            {
              LinkedList<Instruccion> RESULT =null;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		 RESULT = l; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ElseCase",2, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ElseCase ::= 
            {
              LinkedList<Instruccion> RESULT =null;
		 RESULT = new LinkedList(); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("ElseCase",2, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // While ::= WHILE PAP E0 PCIERRE CAP LInst CCIERRE 
            {
              Instruccion RESULT =null;
		TokenValue w = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-6)).value;
		E exp = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-4)).value;
		LinkedList<Instruccion> inst_while = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		 RESULT = new WhileLoop(w.fila, w.columna, exp, inst_while); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("While",7, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // For ::= FOR PAP Asig E0 PUNTOCOMA AsigSinPC PCIERRE CAP LInst CCIERRE 
            {
              Instruccion RESULT =null;
		TokenValue f = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-9)).value;
		Instruccion ini = (Instruccion)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-7)).value;
		E cond = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-6)).value;
		Instruccion paso = (Instruccion)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-4)).value;
		LinkedList<Instruccion> inst_for = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		 RESULT = new ForLoop(f.fila, f.columna, ini, cond, paso, inst_for); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("For",8, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // E0 ::= E0 POR E1 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new EBin(op1.getFila(), BinOps.MUL, op1, op2); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E0",11, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // E0 ::= E0 DIV E1 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new EBin(op1.getFila(), BinOps.DIV, op1, op2); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E0",11, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // E0 ::= E1 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = exp; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E0",11, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // E1 ::= E1 MAS E2 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new EBin(op1.getFila(), BinOps.MAS, op1, op2); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E1",12, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // E1 ::= E1 RESTA E2 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new EBin(op1.getFila(), BinOps.RESTA, op1, op2); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E1",12, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // E1 ::= E2 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = exp; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E1",12, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // E2 ::= E2 IGUALIGUAL E3 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new EBin(op1.getFila(), BinOps.IGUAL, op1, op2); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E2",13, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // E2 ::= E3 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = exp; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E2",13, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // E3 ::= E3 MAYOR E4 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new EBin(op1.getFila(), BinOps.MAYOR, op1, op2); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E3",14, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // E3 ::= E3 MENOR E4 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new EBin(op1.getFila(), BinOps.MENOR, op1, op2); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E3",14, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // E3 ::= E3 MAYORIGUAL E4 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new EBin(op1.getFila(), BinOps.MAYORIGUAL, op1, op2); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E3",14, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // E3 ::= E3 MENORIGUAL E4 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new EBin(op1.getFila(), BinOps.MENORIGUAL, op1, op2); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E3",14, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // E3 ::= E4 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = exp; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E3",14, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // E4 ::= E4 TAMBIENBOOL E5 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new EBin(op1.getFila(), BinOps.AND, op1, op2); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E4",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // E4 ::= E4 OBOOL E5 
            {
              E RESULT =null;
		E op1 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-2)).value;
		E op2 = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new EBin(op1.getFila(), BinOps.OR, op1, op2); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E4",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // E4 ::= E5 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = exp; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E4",15, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // E5 ::= ENT 
            {
              E RESULT =null;
		TokenValue value = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new Num(value.fila, value.columna, value.lexema); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E5",16, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // E5 ::= REAL 
            {
              E RESULT =null;
		TokenValue value = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new Real(value.fila, value.columna, value.lexema); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E5",16, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // E5 ::= TRUE 
            {
              E RESULT =null;
		TokenValue t = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new BoolValue(t.fila, t.columna, "verdadero"); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E5",16, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // E5 ::= FALSE 
            {
              E RESULT =null;
		TokenValue f = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new BoolValue(f.fila, f.columna, "falso"); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E5",16, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // E5 ::= IDEN 
            {
              E RESULT =null;
		TokenValue id = (TokenValue)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.peek()).value;
		 RESULT = new Identificador(id.fila, id.columna, id.lexema); 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E5",16, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // E5 ::= PAP E0 PCIERRE 
            {
              E RESULT =null;
		E exp = (E)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoTiny$stack.elementAt(CUP$AnalizadorSintacticoTiny$top-1)).value;
		 RESULT = exp; 
              CUP$AnalizadorSintacticoTiny$result = parser.getSymbolFactory().newSymbol("E5",16, RESULT);
            }
          return CUP$AnalizadorSintacticoTiny$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$AnalizadorSintacticoTiny$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoTiny$do_action(
    int                        CUP$AnalizadorSintacticoTiny$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoTiny$parser,
    java.util.Stack            CUP$AnalizadorSintacticoTiny$stack,
    int                        CUP$AnalizadorSintacticoTiny$top)
    throws java.lang.Exception
    {
              return CUP$AnalizadorSintacticoTiny$do_action_part00000000(
                               CUP$AnalizadorSintacticoTiny$act_num,
                               CUP$AnalizadorSintacticoTiny$parser,
                               CUP$AnalizadorSintacticoTiny$stack,
                               CUP$AnalizadorSintacticoTiny$top);
    }
}

