
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Jan 18 13:01:27 CET 2026
//----------------------------------------------------

package constructorAST.constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 27;
  public static final int MENOR = 21;
  public static final int IGUALIGUAL = 19;
  public static final int ELSE = 3;
  public static final int DOSPUNTOS = 33;
  public static final int MENORIGUAL = 23;
  public static final int IGUAL = 18;
  public static final int WHILE = 4;
  public static final int IDEN = 11;
  public static final int CCIERRE = 29;
  public static final int TRUE = 9;
  public static final int IF = 2;
  public static final int POR = 16;
  public static final int CAP = 28;
  public static final int BARRABAJA = 34;
  public static final int OBOOL = 25;
  public static final int MAYOR = 20;
  public static final int EOF = 0;
  public static final int DIV = 17;
  public static final int PAP = 26;
  public static final int MAYORIGUAL = 22;
  public static final int TIPO_BOOL = 7;
  public static final int FALSE = 10;
  public static final int error = 1;
  public static final int TIPO_ENT = 6;
  public static final int INTERAPERTURA = 31;
  public static final int TIPO_REAL = 8;
  public static final int PUNTOCOMA = 30;
  public static final int FOR = 5;
  public static final int REAL = 13;
  public static final int ENT = 12;
  public static final int TAMBIENBOOL = 24;
  public static final int MAS = 14;
  public static final int INTERCIERRE = 32;
  public static final int RESTA = 15;
}

